heliport:
  centreville:
    x: -444.5
    y: 81.0
    z: -434.
  zonene:
    x: 349.5
    y: 84.0
    z: -393.5
  zones:
    x: -179.5
    y: 97.0
    z: 605.5
  zonemilli:
    x: 553.5
    y: 76.0
    z: 704.5
time:
  playerhaskilled: 30
  doorpass: 10
  handpass: 2