name: Fireland
version: 3.0
author: Byxis
main: fr.byxis.main.Main
api-version: 1.19
depend:
  - Vault
  - ProtocolLib
commands:
  speedfly:
    description: Permet de changer la vitesse de vol
    permission: fireland.command.flyspeed
    aliases: [sf,fs,flyspeed]
  heliport:
    description: Permet de voir la map et se teleporter
    permission: fireland.command.heliport
    aliases: [menu]
  thirst:
    description: Permet de modifier la barre de soif
    permission: fireland.command.thirst
  cure:
    description: Permet d'enlever l'infection
    permission: fireland.command.cure
  infect:
    description: Permet d'ajouter  une infection
    permission: fireland.command.infect
  rally:
    description: Permet de rallier tous les zombies proche de 50 block sur un joueur
  shop:
    description: Permet d'ouvrir les differents shops disponible
    permission: fireland.command.shop
  bank:
    description: Permet d'ouvrir la banque
    permission: fireland.command.bank
  rename:
    description: Permet de renommer les items dans la main
    permission: fireland.command.rename
  stack:
    description: Permet de stack les items
    permission: fireland.command.stack
  ambientsound:
    description: Permet de desactiver les sons d'ambiance
    permission: fireland.command.ambientsound
  n:
    description: Active et desative la night vision pour les administrateurs
    permission: fireland.command.n
    aliases: [nv,nightv,nightvision,vision,vis]
  faction:
    description: commandes destinees aux actions des factions
    aliases: [f,fac]
  discord:
    description: renvoie le discord officiel de Fireland
  jeton:
    description: commandes pour les jetons
    permission: fireland.command.jeton
    aliases: [ jt, jetons ]
  rang:
    description: commandes pour les rangs
    aliases: [rangs]
  workshop:
    description: commandes pour le workshop
    aliases: [ ws ]
  intendant:
    description: commande pour l intendant
    permission: fireland.command.intendant
  playpacket:
    description: commandes de test pour les packets
    permission: fireland.command.playpacket