heliport:
  centreville:
    x: -444.5
    y: 86.0
    z: -434.
  zonene:
    x: 349.5
    y: 84.0
    z: -393.5
  zones:
    x: -179.5
    y: 97.0
    z: 605.5
  zonemilli:
    x: 576
    y: 80
    z: 692 
time:
  playerhaskilled: 150
  doorpass: 10
  handpass: 2